name: Publish to Github Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn predeploy

      - name: Deploy to GitHub Pages
        run: yarn deploy
