# .github/workflows/publish-githubio.yml
name: Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build website
        run: |
          flutter pub get
          flutter build web

      - name: Upload to github.io
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: "build/web"
